### PR TITLE
Tiled button texture and slight spritesheet improvement

### PR DESCRIPTION
**Pull request by nessemis**
Allowed sprites in the spritesheet to be drawn tiled (repeated instead of stretched), and improved readability of the spritesheet class.

### CODE REVIEW

**Review by jensj12 — CHANGES_REQUESTED** [review]
Keys in the inventory are incorrectly tiled.

**Comment by nessemis** [comment]
@jensj12 fixed keysprite and merged with latest master

**Review by maxmeijer42 — APPROVED** [review]

**Comment by maxmeijer42** [comment]
I don't know what happened to this branch, but the rebase wasn't done correctly. I just did

```git
git fetch
git reset --soft origin/master
git commit
```

to fix it as we're going to squash merge it anyway.

**Comment by nessemis** [comment]
@jensj12  please review again

**Review by jensj12 — APPROVED** [review]

**Pull request merged**
