### PR TITLE
Add first 2 levels

### PR DESCRIPTION
**Pull request by jensj12**
Happy playing!

### CODE REVIEW

**Comment by jorisBarkema** [comment]
I can't seem to play the levels, shouldn't they show up when pressing begin game, or maybe even better if more work, something like a separate tutorial button on the main screen?

**Comment by jensj12** [comment]
The question is, where to add them so they get copied to the correct folder. The current method clearly doesn't work.

**Comment by jorisBarkema** [comment]
A new folder tutorial inside the levels folder maybe?

**Review by jorisBarkema — CHANGES_REQUESTED** [review]
They're still not showing up for me after clicking begin game, in neither debug nor release mode.

**Comment by jensj12** [comment]
Tried moving them to a different item group, does that make a difference?

**Review by jorisBarkema — APPROVED** [review]

**Comment by jorisBarkema** [comment]
Yes, I can see them!

**Pull request merged**
