### PR TITLE
New resize fix

### PR DESCRIPTION
**Pull request by jensj12**
Seems to be the correct branch.

### CODE REVIEW

**Comment by jensj12** [comment]
I have no idea how to fix the merge issues, nor if this is the correct version. @nessemis ?

**Comment by maxmeijer42** [comment]
Merge conflict was a rename I did.

**Comment by jensj12** [comment]
If it all works, feel free to approve and merge this.

**Comment by jensj12** [comment]
Default load directory is wrong.

**Review by maxmeijer42 — APPROVED** [review]

**Comment by maxmeijer42** [comment]
What do you mean? It's %appdata%/TheAMazeIngEscape/levels.

**Comment by jensj12** [comment]
Inside the editor

**Comment by maxmeijer42** [comment]
Oh

**Comment by nessemis** [comment]
@jensj12  @maxmeijer42  I was just a little to caught up fixing issues with the AI, hence the delay. The graphics resize branch should contain exactly the same changes this one does except the added buttons. This branch was basically used as a placeholder to copy the necessary changes for resizing to work into the master branch. Then I used reset --hard on the other branch.

**Comment by jensj12** [comment]
The game will now be sent to sergey for judging. No more PR's will be merged.

**Comment by jensj12** [comment]
button on game over screen is incorrectly positioned

**Comment by jensj12** [comment]
Can you fix that within one minute @maxmeijer42 @nessemis ? (please react before doing so) Lisanne needs sleep

**Comment by maxmeijer42** [comment]
I cannot seem to reproduce the problem

**Comment by maxmeijer42** [comment]
http://puu.sh/tIXPp/e5923006d8.jpg

**Pull request merged**
