### PR TITLE
Load level settings

### PR DESCRIPTION
**Pull request by nessemis**
Enable the box to the right of the loadlevel to show avaible Player types an difficulties. The playertypes and difficulties are tied to a dictonary for now.

### CODE REVIEW

**Comment by LisanneW** [comment]
If you try to select a level on the left side, the level right underneath it in the list will be loaded. Also shouldn't you be able to pick a difficulty level if you play a randomly generated maze with a humanplayer?

**Comment by maxmeijer42** [comment]
Well, I think the difficulty applies to the AI, not to the MazeGenerator. AFAIK we are not going to implement difficulty levels for the generator

**Comment by jensj12** [comment]
The generator has difficulty settings...

**Comment by jensj12** [comment]
There's an error while building the game. One of the used strings does not exits (probably a merge mistake).

**Review by jensj12 — APPROVED** [review]

**Pull request merged**
