### PR TITLE
added the new/changed sprites

### PR DESCRIPTION
**Pull request by jorisBarkema**
also removed the old ones, NOT ADDED to content.mgcb

### CODE REVIEW

**Review by jensj12 — CHANGES_REQUESTED** [review]
Player is not updated to allow animations, so either update the player code or remove the updated sprite.
How is the EndTile meant to be used? Looks like it must be between two walls, which won't always be the case.

**Comment by jorisBarkema** [comment]
I'll remove the updated sprite for the player, as for the EndTile I think it always is between two walls, at least I assumed since it's a prison escape game that the end has to be on the edge, and the edge is all walls.

**Comment by jensj12** [comment]
In that case we need two sprites, horizontal and vertical.

**Comment by jorisBarkema** [comment]
Oops forgot about that....Will make and add the other one now.

**Review by jensj12 — APPROVED** [review]

**Pull request merged**
