### PR TITLE
update door overlays

### PR DESCRIPTION
**Pull request by jorisBarkema**
Updated one of the door overlays so they match in intensity, added the overlay spritesheet with colors, because I thought we weren't using individual overlays anymore

didn't remove the individual overlays because they're still being used I see, can always do that later.

### CODE REVIEW

**Comment by jensj12** [comment]
Please keep the description (reasoning, extra comments) out of the title. Put it in the description instead.

I prefer the spritesheet to be 6x3 (one column per color), and don't forget to put the @6x3 in the name of the sprite (instead of 'spritesheet').

Additionally, the code is ready to handle run-time color blending, so I'm not sure if we're going to switch to a spritesheet of colors. If not, I'd like to see both overlays and both doors in a spritesheet instead of seperate sprites.

**Comment by jorisBarkema** [comment]
Yes I figured out how the column thing works while working on the player animations, before I continue with this I think it's good to figure out what we want exactly.

**Comment by jensj12** [comment]
Abandon the spritesheet and just update the white overlays to match in intensity.

**Comment by jorisBarkema** [comment]
They match, and I removed the old spritesheet.

**Comment by jensj12** [comment]
Don't reorder content.mgcb if it's not necessary, if someone else changed something (s)he would have a merge conflict.

**Pull request closed without merging**
