### PR TITLE
Level editor resize

### PR DESCRIPTION
**Pull request by nessemis**
The map in the level editor can now be resized by pressing the button "new"

Uses the EdgeTextures branch.

### CODE REVIEW

**Review by LisanneW — DISMISSED** [review]
When choosing dimensions for the new maze, it's not possible to choose anything between 20 and 99 because it adds a 1 if everything is removed.

**Comment by jensj12** [comment]
Remove commits from other branch, that should fix most merge issues

**Comment by jensj12** [comment]
Resizing doesn't add the walls to the prison edge

**Comment by jensj12** [comment]
1. Resize maze in editor (smaller)
2. Go back to main menu
3. Go back to editor
4. Crash!

**Review by jensj12 — APPROVED** [review]

**Pull request merged**
