### PR TITLE
Abstract Tile class

### PR DESCRIPTION
**Pull request by maxmeijer42**
Nodig voor het toevoegen van nieuwe type tiles

### CODE REVIEW

**Review by jensj12 — COMMENTED** [review]
Looks good, but documentation is inconsistent. Are we adding comments to all of the implemented functions or only to those in the abstract tile class? It's mixed in WallTile

**Comment by maxmeijer42** [comment]
You're right. I think it's better not to document overridde methods, just the abstract ones. Comments can be added to clarify how the method is overriding the abstract one.

**Review by jensj12 — CHANGES_REQUESTED** [review]
Undo the merge with the non-master branches and rebase

**Comment by maxmeijer42** [comment]
Done

**Comment by jensj12** [comment]
It's not up to date with the master branch yet

**Comment by maxmeijer42** [comment]
Oh of course new commits

**Comment by maxmeijer42** [comment]
Nu wel

**Review by jensj12 — APPROVED** [review]

**Pull request merged**
