### PR TITLE
Monte Carlo AI 2

### PR DESCRIPTION
**Pull request by jensj12**
Replaces #104, still work in progress.

### CODE REVIEW

**Comment by jensj12** [comment]
This should be merged (without defaulting to use the AI) so the maze setup settings can be fully implemented.

**Comment by jensj12** [comment]
Could some check if getlocationafteraction always returns the correct location? From what I've seen from debugging inside MC, this may be the cause of the issues.

**Comment by maxmeijer42** [comment]
Pretty sure it doesn't. It should be protected. It's a helper function used inside the Tile class. Do not use it outside of the tile class.
:

**Comment by jensj12** [comment]
Merged via #195

**Pull request closed without merging**
