### PR TITLE
Added win/lose screens, added icon

### PR DESCRIPTION
**Pull request by BNijmeijer**
The icon is the intended icon for the executable. Currently it's
defaulted to 128x128, but can be magnified to fit the proper dimensions.

### CODE REVIEW

**Comment by jorisBarkema** [comment]
Lot of empty lines changed, I don't know if that can cause issues for other merges, safer to fix that first I think.

**Comment by BNijmeijer** [comment]
fixed

**Comment by jorisBarkema** [comment]
You either forgot to sync or something else went wrong, I don't see any changes. I'm going to sleep now.

Only other comment from me is that the three stripes on the icon seem a bit weird, if you want to add taht kind of stripes maybe make them start from the player and a little thinner. Personally I don't think they're necessary it should be clear he's running from the way you draw the player.

**Comment by BNijmeijer** [comment]
Should be sync'd now

**Review by jensj12 — APPROVED** [review]

**Pull request merged**
